/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as ArticleArticleIdRouteImport } from './routes/article.$articleId'
import { Route as AdminWriteRouteImport } from './routes/admin.write'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminEntriesRouteImport } from './routes/admin.entries'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleArticleIdRoute = ArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWriteRoute = AdminWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntriesRoute = AdminEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/author': typeof AuthorRoute
  '/bookmarks': typeof BookmarksRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/entries': typeof AdminEntriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/write': typeof AdminWriteRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/author': typeof AuthorRoute
  '/bookmarks': typeof BookmarksRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/entries': typeof AdminEntriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/write': typeof AdminWriteRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/author': typeof AuthorRoute
  '/bookmarks': typeof BookmarksRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/entries': typeof AdminEntriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/write': typeof AdminWriteRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/author'
    | '/bookmarks'
    | '/profile'
    | '/search'
    | '/admin/comments'
    | '/admin/entries'
    | '/admin/media'
    | '/admin/tags'
    | '/admin/write'
    | '/article/$articleId'
    | '/post/$postId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/author'
    | '/bookmarks'
    | '/profile'
    | '/search'
    | '/admin/comments'
    | '/admin/entries'
    | '/admin/media'
    | '/admin/tags'
    | '/admin/write'
    | '/article/$articleId'
    | '/post/$postId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/author'
    | '/bookmarks'
    | '/profile'
    | '/search'
    | '/admin/comments'
    | '/admin/entries'
    | '/admin/media'
    | '/admin/tags'
    | '/admin/write'
    | '/article/$articleId'
    | '/post/$postId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthorRoute: typeof AuthorRoute
  BookmarksRoute: typeof BookmarksRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  ArticleArticleIdRoute: typeof ArticleArticleIdRoute
  PostPostIdRoute: typeof PostPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$articleId': {
      id: '/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/article/$articleId'
      preLoaderRoute: typeof ArticleArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/write': {
      id: '/admin/write'
      path: '/write'
      fullPath: '/admin/write'
      preLoaderRoute: typeof AdminWriteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entries': {
      id: '/admin/entries'
      path: '/entries'
      fullPath: '/admin/entries'
      preLoaderRoute: typeof AdminEntriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminEntriesRoute: typeof AdminEntriesRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminWriteRoute: typeof AdminWriteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommentsRoute: AdminCommentsRoute,
  AdminEntriesRoute: AdminEntriesRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminWriteRoute: AdminWriteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthorRoute: AuthorRoute,
  BookmarksRoute: BookmarksRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  ArticleArticleIdRoute: ArticleArticleIdRoute,
  PostPostIdRoute: PostPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
